### ISSUE TITLE
Question about handling of columns that have a database-level default value

### ISSUE THREAD

**Issue by danielrhodeswarp** [simonhamp/laravel-nova-csv-import#11]
Not sure if this is how it is supposed / designed to work, but here's something unexpected that I noticed:

I am filling a simple, three column table with the import tool. Two of the fields are required at the database level, one field ("used") has a database-level default value.

My observation is that I always needed the "used" field to be explicitly in the CSV file for importing to work. This is the case regardless of "used" being nullable or not (I tried both configurations).

I would have expected the Import tool to simply put the database-level default in for columns that are not explicitly in the CSV file.

Just reporting the observation really and happy to be educated ;-)

**Comment by danielrhodeswarp** [comment]
Something to do with the code and the package using Eloquent models as a primary resource (and not the actual SQL table structure)?

**Comment by danielrhodeswarp** [comment]
Thank you for this package Simon. I'm only reporting issues because I love it so much :D

**Comment by simonhamp** [comment]
Thanks for using it in earnest @danielrhodeswarp and taking the time to report issues. I really appreciate it.

The import tool won't read the database default values to place into your fields as you import the data. If Nova has some understanding of those columns or your model includes any validation that may prevent data from saving without appropriate values, your import will most certainly fail.

This is a big assumption though and I would definitely need to see more about your data, data structure, models and resources to see if I can replicate this issue. I'm happy to investigate - if you can provide this detail - when I have time.
