### ISSUE TITLE
Option to use database table fields instead of resource

### ISSUE THREAD

**Issue by Dontorpedo** [simonhamp/laravel-nova-csv-import#14]
Hello,

Many of my resources have fields with are only visible in the database, but have to be filled.. 

a option for using fields from the coresponding table would be ideal for this.. 

thanks
D

**Comment by simonhamp** [comment]
I agree @Dontorpedo, that might be a nice feature in some circumstances.

I'm open to PRs if anyone fancies giving this a go.
