### ISSUE TITLE
coma separated csv option

### ISSUE THREAD

**Issue by Dontorpedo** [simonhamp/laravel-nova-csv-import#15]
Hi,

In Europe we use mostly Comaseparated csv files, not semicolon like in US.. a option or something to accept both would be nice..

**Comment by simonhamp** [comment]
@Dontorpedo you can customise the importer classed used by publishing and overriding the config. Would that help?

**Comment by FrodeMMeling** [comment]
That would help. I just hit same issue.. Maybe support for xlsx could also be added?

**Comment by simonhamp** [comment]
@FrodeMMeling would you mind opening a new ticket for that?
