### ISSUE TITLE
FEATURE REQUEST: Update existing entries

### ISSUE THREAD

**Issue by jeremy-skaraudio** [simonhamp/laravel-nova-csv-import#25]
Hi not sure if it is possible and I tried to don't myself but is there a way to update existing DB entries when you import currently it only creates new entries.

and if not is there a way I can make a feature request I'm sure there are more people that would love to be able to update instead of creating new entires

**Comment by simonhamp** [comment]
Thanks for using the plugin @jeremy-skaraudio. It doesn’t currently support updating of records, but it’s definitely something that I’d like it to have.

We’ve actually already received this as a feature request (#12), so I’m going to close this one in favour of keeping a single instance of feature requests around.

If you’d like to add further comments on this, please add them to #12.

Thanks 😊
