### ISSUE TITLE
Importer.php $this->attributes uninitialized and throw Exception on foreach

### ISSUE THREAD

**Issue by redsend** [simonhamp/laravel-nova-csv-import#34]
This is the point where there is the error, I'm trying to debug to understand why it happens. As you can see, the foreach on the attributes fails, because $this->attributes is null

<img width="1561" alt="Schermata 2022-01-27 alle 11 17 29" src="https://user-images.githubusercontent.com/2745269/151339510-70e51671-1c09-47df-b19e-5e18473c0b2f.png">
.

**Comment by dnl4** [comment]
Same here. Can't figure why.

Laravel 8
Laravel nova 3.30.0
Fresh installation

**Comment by falconsmilie** [comment]
\SimonHamp\LaravelNovaCsvImport\Importer line 135.

<img width="481" alt="Screen Shot 2022-02-10 at 13 06 54" src="https://user-images.githubusercontent.com/1234911/153405897-740524b9-e11b-4693-aba7-994fe24d6c5c.png">

**Comment by falconsmilie** [comment]
From the [Controller](https://github.com/simonhamp/laravel-nova-csv-import/blob/1684d03afcad7f5da38adf10f752014f0c2430bf/src/Http/Controllers/UploadController.php#L25) where it calls [toCollection()](https://github.com/SpartnerNL/Laravel-Excel/blob/eb31f30d72c51c3fb11644b636945accbe50404f/src/Concerns/Importable.php#L75) on the [Importer](https://github.com/simonhamp/laravel-nova-csv-import/blob/main/src/Importer.php), the Importer members are all `null`.

**Comment by falconsmilie** [comment]
@simonhamp [this is the change that broke it](https://github.com/simonhamp/laravel-nova-csv-import/commit/347675c18eba1e4a390f3baf338d9c8ae5894a9e).

I you revert that change the upload will work, but then you get some other issues. I have this weird behaviour where if I don't set `public static function canImportResource(Request $request)` on at least one Nova resource, it goes into an infinite loop. Strangley enough the resource you implement that method on is then not listed in the Resource dropdown.

It also doesn't seem to support CSV separated by `;`.

**Comment by falconsmilie** [comment]
I'm willing, but i'm not sure if I'm able ... the behaviour is not consistent :/ 

I just renabled the change i mentioned above and it worked ... 

But in any case, with the `map()` or not, i still get the weird behaviour with a User model not showing when it is the only one which is enabled, thus my "choose resource" dropdown is empty.

I'll spend some more time looking at it.

**Comment by falconsmilie** [comment]
I've only been working with CSV and needed to set some config values in the [maatwebsite/excel config](https://github.com/SpartnerNL/Laravel-Excel/blob/3.1/config/excel.php) so it would accept `;` separator. I can never get this tool to accept XLSX, i don't know why, upload always fails.

Here's what i've found in reference to working with CSV.

- **_upload_** will not work when the [Importer](https://github.com/simonhamp/laravel-nova-csv-import/blob/main/src/Importer.php) class is implementing `WithMapping`.
- **_import_** will not work when the [Importer](https://github.com/simonhamp/laravel-nova-csv-import/blob/main/src/Importer.php) class is **_not_** implementing `WithMapping`.

As i noted earlier, there is an infinite loop scenario which can occur. It seems to happen when you have resources which extend the same model. For example two models extending Authenticatable.

**Comment by sergioaraos** [comment]
Any news about this issue?

Laravel 8.83
Laravel nova 3.31.0

**Comment by simonhamp** [comment]
Folks, simply sharing a screenshot of the code (I know the code 😂) or reporting which versions of the main components that you're running is not much help.

💡 If you would like me to assist in solving this issue, you need to make it easy for me to replicate the problem. For that you should share the following:

1. A sample of your data file (a couple of rows is enough)
2. The configuration of your Nova resource (i.e. the fields)
3. The model class that it interrogates
4. The migration for that table

If for some reason you are uncomfortable or unable to share that code here, let me know and I'll provide another way for you to share 👍🏼
