### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by leesouthwart** [simonhamp/laravel-nova-csv-import#35]
I'm just trying to import a very simple csv file but getting this error.

The file is simply

id,amount
1,200
2,300
3,400

Which is just being used as a test file.

Versions:

Laravel 8.6
Nova 3.29.0

Is there something obvious i'm missing?

edit: this is happening when I press the 'import' button after selecting a file, not after mapping my fields etc

**Comment by lovecoding-git** [comment]
@leesouthwart  were you able to solve this issue? I'm seeing the same issue now.
