### ISSUE TITLE
 "foreach() argument must be of type array|object, null given"

### ISSUE THREAD

**Issue by lovecoding-git** [simonhamp/laravel-nova-csv-import#38]
-Laravel Version 9
-Nova 3.29
-CSV 0.3.0

When I import csv file, I'm getting 422 error and error screen is this.

![image](https://user-images.githubusercontent.com/61916777/167062531-ad884873-04f0-4662-a8d2-7f7a677d7430.png)

**Comment by simonhamp** [comment]
@lovecoding-git Are you able to share the file you're importing and the details of which version of this package you're using?

**Comment by ninjasitm** [comment]
Seeing the same issue with the same versions as @lovecoding-git . CSV is the following:

```
word,language
asdioj,en
asddpoikj,en
aofij,en
afiojo,en
```

**Comment by matthijs-neijenhuijs** [comment]
same problem here.

**Comment by simonhamp** [comment]
Hey folks, so I think v0.3.0 has some issues.

I'm afraid I haven't used it much at that stage so I'm less familiar with the issues presenting there.

If you're not running Nova 4 yet, please use an older version (<0.3) of this package. Please note however, that I'm not actively supporting these older versions for free.

If you're 'stuck' on Nova <4 and need a fix or other work on this package that you're not prepared to PR, let's discuss how you can contract me to do the needed work.
