### ISSUE TITLE
Prevent duplicates 

### ISSUE THREAD

**Issue by HeadStudios** [simonhamp/laravel-nova-csv-import#70]
How should I modify my code to prevent duplicates (based on email column of Contact model) when importing through CSV and ideally showing error on frontend? Below is my attempts so far:
https://chat.openai.com/share/aa72b7fb-fb5f-432c-b295-a2e68c3e61fd

Thank you!

**Comment by simonhamp** [comment]
That's a lot to run through 😅 

Having not investigated the full history of your ChatGPT session, I want to indicate that I believe CSV Import already supports what you're trying to achieve; **you shouldn't need to change any code within the package to do what you're trying to do here**

Your resource and database just need to be set up correctly:

1. [Add a `unique` validation rule](https://laravel.com/docs/10.x/validation#rule-unique) to your [`email` field](https://nova.laravel.com/docs/4.0/resources/validation.html) in your Nova Resource definition
2. **OPTIONAL** (but highly recommended): [Add a `UNIQUE` index](https://laravel.com/docs/10.x/migrations#creating-indexes) to your `email` column

The import summary in the latest versions of CSV Import should provide you with enough detail to know what has happened:

![](https://github.com/simonhamp/laravel-nova-csv-import/blob/main/screenshots/review.png?raw=true)

**Comment by HeadStudios** [comment]
Thank you so much!
