### ISSUE TITLE
I am not able to link resource with csv Import functionality

### ISSUE THREAD

**Issue by softsnare** [simonhamp/laravel-nova-csv-import#9]
![image](https://user-images.githubusercontent.com/12980119/58634169-3c877c80-8308-11e9-8002-7575a5d8e8a8.png)
Hello Simon,
Good evening!

Please find the attachment for the image of page I am receiving after adding the component to tools.

Please it will be a great help to me if You could help in proceeding further in the same.

Thank you

**Comment by softsnare** [comment]
This is an exception I am receiving.

[2019-05-30 12:40:42] production.ERROR: md5_file(): Filename cannot be empty {"userId":"230fbff0-5439-11e9-ab34-69ce6f383d7d","email":"admin@test.com","exception":"[object] (ErrorException(code: 0): md5_file(): Filename cannot be empty at D:\\xampp\\htdocs\\laravel-crm\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php:109)

**Comment by softsnare** [comment]
$file->getRealPath()

this method is returning empty

**Comment by simonhamp** [comment]
It looks like there's a bug here on Windows / XAMPP in the Filesystem library and seems like it's not specifically related to this package. Unfortunately I don't use either of those so it's going to be a little tricky for me to debug.

I'm going to close this issue, as I suspect you may face this issue elsewhere if you were to use the `Illuminate\Support\Facades\File::hash()` method, which would highlight a problem with your local development setup.

If anyone else can provide any insight, please feel free to assist.
